<#
.SYNOPSIS
    Validates Azure Architecture Builder PowerShell deployment scripts for 100% deployability.

.DESCRIPTION
    This script performs comprehensive validation checks on Azure PowerShell deployment scripts
    generated by Azure Architecture Builder to ensure they are ready for deployment without errors.
    
    It checks for:
    - Valid Azure PowerShell module installation
    - Required field placeholders (<REQUIRED:...>)
    - Syntax errors
    - Resource naming conflicts
    - Missing dependencies
    - Authentication requirements

.PARAMETER ScriptPath
    Path to the PowerShell deployment script to validate.

.PARAMETER CheckAzModule
    Validates that required Azure PowerShell modules are installed.

.PARAMETER DetailedReport
    Generates a detailed validation report with recommendations.

.EXAMPLE
    .\Validate-AzureDeployment.ps1 -ScriptPath ".\azure-deploy.ps1" -DetailedReport

.EXAMPLE
    .\Validate-AzureDeployment.ps1 -ScriptPath ".\azure-deploy.ps1" -CheckAzModule

.NOTES
    Author: Azure Architecture Builder
    Version: 1.0.0
    Generated: 2026-07-17
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory=$true, Position=0)]
    [ValidateScript({Test-Path $_ -PathType Leaf})]
    [string]$ScriptPath,
    
    [Parameter(Mandatory=$false)]
    [switch]$CheckAzModule,
    
    [Parameter(Mandatory=$false)]
    [switch]$DetailedReport
)

# Initialize validation results
$ValidationResults = @{
    IsValid = $true
    Errors = @()
    Warnings = @()
    Info = @()
    RequiredFields = @()
    MissingModules = @()
    ResourceCount = 0
    DeploymentReady = $false
}

Write-Host "`n=====================================" -ForegroundColor Cyan
Write-Host "Azure Deployment Validation Tool" -ForegroundColor Cyan
Write-Host "=====================================" -ForegroundColor Cyan
Write-Host "Script: $ScriptPath`n" -ForegroundColor White

# Read the script content
try {
    $ScriptContent = Get-Content -Path $ScriptPath -Raw
    $ValidationResults.Info += "Successfully loaded deployment script"
}
catch {
    $ValidationResults.IsValid = $false
    $ValidationResults.Errors += "Failed to read script file: $_"
    Write-Host "[ERROR] Failed to read script file: $_" -ForegroundColor Red
    return $ValidationResults
}

# Check 1: Validate script syntax
Write-Host "[CHECK 1] Validating PowerShell syntax..." -ForegroundColor Yellow
try {
    $Errors = $null
    $null = [System.Management.Automation.PSParser]::Tokenize($ScriptContent, [ref]$Errors)
    
    if ($Errors.Count -gt 0) {
        $ValidationResults.IsValid = $false
        foreach ($Error in $Errors) {
            $ValidationResults.Errors += "Syntax error at line $($Error.Token.StartLine): $($Error.Message)"
        }
        Write-Host "  ✗ Found $($Errors.Count) syntax error(s)" -ForegroundColor Red
    }
    else {
        Write-Host "  ✓ Syntax validation passed" -ForegroundColor Green
    }
}
catch {
    $ValidationResults.Warnings += "Could not perform syntax validation: $_"
    Write-Host "  ! Warning: Could not perform syntax validation" -ForegroundColor Yellow
}

# Check 2: Find required field placeholders
Write-Host "[CHECK 2] Checking for required field placeholders..." -ForegroundColor Yellow
$RequiredFieldPattern = '<REQUIRED:([^>]+)>'
$RequiredFieldMatches = [regex]::Matches($ScriptContent, $RequiredFieldPattern)

if ($RequiredFieldMatches.Count -gt 0) {
    $ValidationResults.IsValid = $false
    $ValidationResults.DeploymentReady = $false
    
    $UniqueFields = $RequiredFieldMatches | ForEach-Object { $_.Groups[1].Value } | Select-Object -Unique
    
    foreach ($Field in $UniqueFields) {
        $Count = ($RequiredFieldMatches | Where-Object { $_.Groups[1].Value -eq $Field }).Count
        $ValidationResults.RequiredFields += @{
            Field = $Field
            Occurrences = $Count
        }
        $ValidationResults.Errors += "REQUIRED field missing: $Field (found $Count occurrence(s))"
    }
    
    Write-Host "  ✗ Found $($UniqueFields.Count) required field(s) that must be filled:" -ForegroundColor Red
    foreach ($Field in $ValidationResults.RequiredFields) {
        Write-Host "    - $($Field.Field) ($($Field.Occurrences) occurrence(s))" -ForegroundColor Red
    }
}
else {
    Write-Host "  ✓ No required field placeholders found" -ForegroundColor Green
}

# Check 3: Count resources to be deployed
Write-Host "[CHECK 3] Counting resources..." -ForegroundColor Yellow
$ResourceCommands = @(
    'New-AzVirtualMachine',
    'New-AzVM',
    'New-AzVmss',
    'New-AzAksCluster',
    'New-AzFunctionApp',
    'New-AzContainerApp',
    'New-AzFirewall',
    'New-AzApplicationGateway',
    'New-AzLoadBalancer',
    'New-AzVirtualNetworkGateway',
    'New-AzBastion',
    'New-AzPrivateEndpoint',
    'New-AzNetworkSecurityGroup',
    'New-AzSqlServer',
    'New-AzCosmosDBAccount',
    'New-AzStorageAccount',
    'New-AzRedisCache',
    'New-AzKeyVault',
    'New-AzWebApp',
    'New-AzApiManagement',
    'New-AzServiceBusNamespace',
    'New-AzEventHubNamespace',
    'New-AzLogicApp',
    'New-AzCognitiveServicesAccount',
    'New-AzOperationalInsightsWorkspace'
)

foreach ($Command in $ResourceCommands) {
    $Matches = [regex]::Matches($ScriptContent, [regex]::Escape($Command))
    $ValidationResults.ResourceCount += $Matches.Count
}

Write-Host "  ℹ Found approximately $($ValidationResults.ResourceCount) resource(s) to deploy" -ForegroundColor Cyan

# Check 4: Validate Azure PowerShell modules if requested
if ($CheckAzModule) {
    Write-Host "[CHECK 4] Checking Azure PowerShell modules..." -ForegroundColor Yellow
    
    $RequiredModules = @(
        'Az.Accounts',
        'Az.Compute',
        'Az.Network',
        'Az.Storage',
        'Az.Resources'
    )
    
    foreach ($Module in $RequiredModules) {
        $Installed = Get-Module -ListAvailable -Name $Module
        if (-not $Installed) {
            $ValidationResults.MissingModules += $Module
            $ValidationResults.Warnings += "Azure module not installed: $Module"
            Write-Host "  ! Warning: Module '$Module' is not installed" -ForegroundColor Yellow
        }
    }
    
    if ($ValidationResults.MissingModules.Count -eq 0) {
        Write-Host "  ✓ All required Azure modules are installed" -ForegroundColor Green
    }
    else {
        Write-Host "  ! Found $($ValidationResults.MissingModules.Count) missing module(s)" -ForegroundColor Yellow
        Write-Host "    Install with: Install-Module -Name Az -AllowClobber -Scope CurrentUser" -ForegroundColor Cyan
    }
}

# Check 5: Look for authentication requirements
Write-Host "[CHECK 5] Checking authentication requirements..." -ForegroundColor Yellow
if ($ScriptContent -match '\$cred|\$password|Get-Credential') {
    $ValidationResults.Warnings += "Script requires credentials to be provided at runtime"
    Write-Host "  ! Script requires user credentials (will prompt during deployment)" -ForegroundColor Yellow
}
else {
    Write-Host "  ✓ No interactive credential prompts detected" -ForegroundColor Green
}

# Check 6: Validate subscription context requirements
Write-Host "[CHECK 6] Checking subscription requirements..." -ForegroundColor Yellow
if ($ScriptContent -match 'Set-AzContext') {
    Write-Host "  ℹ Script will set Azure subscription context" -ForegroundColor Cyan
    $ValidationResults.Info += "Script includes subscription context switching"
}
else {
    $ValidationResults.Warnings += "No subscription context setting found - ensure you're in the correct subscription"
    Write-Host "  ! No subscription context switching found" -ForegroundColor Yellow
    Write-Host "    Run 'Set-AzContext -Subscription <name>' before deployment" -ForegroundColor Cyan
}

# Check 7: Look for potential naming conflicts
Write-Host "[CHECK 7] Checking for potential resource naming issues..." -ForegroundColor Yellow
$ResourceNamePattern = '-Name\s+"([^"]+)"'
$ResourceNames = [regex]::Matches($ScriptContent, $ResourceNamePattern) | ForEach-Object { $_.Groups[1].Value }
$DuplicateNames = $ResourceNames | Group-Object | Where-Object { $_.Count -gt 1 } | Select-Object -ExpandProperty Name

if ($DuplicateNames.Count -gt 0) {
    $ValidationResults.Warnings += "Found duplicate resource names: $($DuplicateNames -join ', ')"
    Write-Host "  ! Warning: Found $($DuplicateNames.Count) duplicate resource name(s)" -ForegroundColor Yellow
    foreach ($Name in $DuplicateNames) {
        Write-Host "    - $Name" -ForegroundColor Yellow
    }
}
else {
    Write-Host "  ✓ No duplicate resource names detected" -ForegroundColor Green
}

# Determine deployment readiness
$ValidationResults.DeploymentReady = ($ValidationResults.IsValid -and $ValidationResults.RequiredFields.Count -eq 0)

# Display summary
Write-Host "`n=====================================" -ForegroundColor Cyan
Write-Host "Validation Summary" -ForegroundColor Cyan
Write-Host "=====================================" -ForegroundColor Cyan

if ($ValidationResults.DeploymentReady) {
    Write-Host "✓ DEPLOYMENT READY" -ForegroundColor Green -BackgroundColor Black
    Write-Host "`nThe script passed all validation checks and is ready for deployment." -ForegroundColor Green
}
else {
    Write-Host "✗ DEPLOYMENT NOT READY" -ForegroundColor Red -BackgroundColor Black
    Write-Host "`nThe script has validation errors that must be fixed before deployment." -ForegroundColor Red
}

Write-Host "`nStatistics:" -ForegroundColor White
Write-Host "  - Errors: $($ValidationResults.Errors.Count)" -ForegroundColor $(if ($ValidationResults.Errors.Count -eq 0) { 'Green' } else { 'Red' })
Write-Host "  - Warnings: $($ValidationResults.Warnings.Count)" -ForegroundColor $(if ($ValidationResults.Warnings.Count -eq 0) { 'Green' } else { 'Yellow' })
Write-Host "  - Resources to deploy: ~$($ValidationResults.ResourceCount)" -ForegroundColor Cyan
Write-Host "  - Required fields missing: $($ValidationResults.RequiredFields.Count)" -ForegroundColor $(if ($ValidationResults.RequiredFields.Count -eq 0) { 'Green' } else { 'Red' })

# Detailed report
if ($DetailedReport) {
    Write-Host "`n=====================================" -ForegroundColor Cyan
    Write-Host "Detailed Report" -ForegroundColor Cyan
    Write-Host "=====================================" -ForegroundColor Cyan
    
    if ($ValidationResults.Errors.Count -gt 0) {
        Write-Host "`nErrors:" -ForegroundColor Red
        foreach ($Error in $ValidationResults.Errors) {
            Write-Host "  ✗ $Error" -ForegroundColor Red
        }
    }
    
    if ($ValidationResults.Warnings.Count -gt 0) {
        Write-Host "`nWarnings:" -ForegroundColor Yellow
        foreach ($Warning in $ValidationResults.Warnings) {
            Write-Host "  ! $Warning" -ForegroundColor Yellow
        }
    }
    
    if ($ValidationResults.Info.Count -gt 0) {
        Write-Host "`nInformation:" -ForegroundColor Cyan
        foreach ($Info in $ValidationResults.Info) {
            Write-Host "  ℹ $Info" -ForegroundColor Cyan
        }
    }
}

# Recommendations
Write-Host "`n=====================================" -ForegroundColor Cyan
Write-Host "Recommendations" -ForegroundColor Cyan
Write-Host "=====================================" -ForegroundColor Cyan

if ($ValidationResults.RequiredFields.Count -gt 0) {
    Write-Host "`n1. Fill in all required fields marked with <REQUIRED:...> in the script" -ForegroundColor Yellow
    Write-Host "   Search for these placeholders and replace them with actual values:" -ForegroundColor Gray
    foreach ($Field in $ValidationResults.RequiredFields) {
        Write-Host "   - <REQUIRED:$($Field.Field)>" -ForegroundColor Gray
    }
}

if ($ValidationResults.MissingModules.Count -gt 0) {
    Write-Host "`n2. Install missing Azure PowerShell modules:" -ForegroundColor Yellow
    Write-Host "   Install-Module -Name Az -AllowClobber -Scope CurrentUser -Force" -ForegroundColor Cyan
}

Write-Host "`n3. Before deployment, ensure you are authenticated:" -ForegroundColor Yellow
Write-Host "   Connect-AzAccount" -ForegroundColor Cyan
Write-Host "   Set-AzContext -Subscription '<your-subscription-name>'" -ForegroundColor Cyan

Write-Host "`n4. Test in a non-production environment first" -ForegroundColor Yellow
Write-Host "   Consider using -WhatIf parameter where available" -ForegroundColor Gray

Write-Host "`n5. Review resource costs before deployment:" -ForegroundColor Yellow
Write-Host "   Check the cost estimator in Azure Architecture Builder" -ForegroundColor Gray

Write-Host "`n=====================================" -ForegroundColor Cyan
Write-Host "Next Steps" -ForegroundColor Cyan
Write-Host "=====================================" -ForegroundColor Cyan

if ($ValidationResults.DeploymentReady) {
    Write-Host "`nYour script is ready! To deploy:" -ForegroundColor Green
    Write-Host "  1. Connect-AzAccount" -ForegroundColor White
    Write-Host "  2. Set-AzContext -Subscription '<your-subscription>'" -ForegroundColor White
    Write-Host "  3. .\$([System.IO.Path]::GetFileName($ScriptPath))" -ForegroundColor White
}
else {
    Write-Host "`nTo fix validation errors:" -ForegroundColor Red
    Write-Host "  1. Open the script in a text editor" -ForegroundColor White
    Write-Host "  2. Search for '<REQUIRED:' and replace all placeholders" -ForegroundColor White
    Write-Host "  3. Fix any syntax errors reported above" -ForegroundColor White
    Write-Host "  4. Run this validation script again" -ForegroundColor White
    Write-Host "  5. .\Validate-AzureDeployment.ps1 -ScriptPath '$ScriptPath' -CheckAzModule -DetailedReport" -ForegroundColor Cyan
}

Write-Host ""

# Return validation results
return $ValidationResults
